// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/agent.proto

package proto

// DeploymentState represents deployment state.
type DeploymentState int32

const (
	DeploymentState_DEPLOYMENT_STATE_UNSPECIFIED  DeploymentState = 0
	DeploymentState_DEPLOYMENT_STATE_PENDING      DeploymentState = 1
	DeploymentState_DEPLOYMENT_STATE_PREPARING    DeploymentState = 2
	DeploymentState_DEPLOYMENT_STATE_CLONING      DeploymentState = 3
	DeploymentState_DEPLOYMENT_STATE_BUILDING     DeploymentState = 4
	DeploymentState_DEPLOYMENT_STATE_DEPLOYING    DeploymentState = 5
	DeploymentState_DEPLOYMENT_STATE_VERIFYING    DeploymentState = 6
	DeploymentState_DEPLOYMENT_STATE_COMPLETED    DeploymentState = 7
	DeploymentState_DEPLOYMENT_STATE_FAILED       DeploymentState = 8
	DeploymentState_DEPLOYMENT_STATE_CANCELLED    DeploymentState = 9
	DeploymentState_DEPLOYMENT_STATE_ROLLING_BACK DeploymentState = 10
)

func (x DeploymentState) String() string {
	switch x {
	case DeploymentState_DEPLOYMENT_STATE_UNSPECIFIED:
		return "DEPLOYMENT_STATE_UNSPECIFIED"
	case DeploymentState_DEPLOYMENT_STATE_PENDING:
		return "DEPLOYMENT_STATE_PENDING"
	case DeploymentState_DEPLOYMENT_STATE_PREPARING:
		return "DEPLOYMENT_STATE_PREPARING"
	case DeploymentState_DEPLOYMENT_STATE_CLONING:
		return "DEPLOYMENT_STATE_CLONING"
	case DeploymentState_DEPLOYMENT_STATE_BUILDING:
		return "DEPLOYMENT_STATE_BUILDING"
	case DeploymentState_DEPLOYMENT_STATE_DEPLOYING:
		return "DEPLOYMENT_STATE_DEPLOYING"
	case DeploymentState_DEPLOYMENT_STATE_VERIFYING:
		return "DEPLOYMENT_STATE_VERIFYING"
	case DeploymentState_DEPLOYMENT_STATE_COMPLETED:
		return "DEPLOYMENT_STATE_COMPLETED"
	case DeploymentState_DEPLOYMENT_STATE_FAILED:
		return "DEPLOYMENT_STATE_FAILED"
	case DeploymentState_DEPLOYMENT_STATE_CANCELLED:
		return "DEPLOYMENT_STATE_CANCELLED"
	case DeploymentState_DEPLOYMENT_STATE_ROLLING_BACK:
		return "DEPLOYMENT_STATE_ROLLING_BACK"
	default:
		return "UNKNOWN"
	}
}

// LogLevel represents log severity.
type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARN        LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
)

func (x LogLevel) String() string {
	switch x {
	case LogLevel_LOG_LEVEL_UNSPECIFIED:
		return "LOG_LEVEL_UNSPECIFIED"
	case LogLevel_LOG_LEVEL_DEBUG:
		return "LOG_LEVEL_DEBUG"
	case LogLevel_LOG_LEVEL_INFO:
		return "LOG_LEVEL_INFO"
	case LogLevel_LOG_LEVEL_WARN:
		return "LOG_LEVEL_WARN"
	case LogLevel_LOG_LEVEL_ERROR:
		return "LOG_LEVEL_ERROR"
	default:
		return "UNKNOWN"
	}
}

// RegisterRequest is sent by agent to register with master.
type RegisterRequest struct {
	AgentId      string             `json:"agent_id,omitempty"`
	Token        string             `json:"token,omitempty"`
	Hostname     string             `json:"hostname,omitempty"`
	Labels       map[string]string  `json:"labels,omitempty"`
	Capabilities *AgentCapabilities `json:"capabilities,omitempty"`
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRequest) GetCapabilities() *AgentCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// Reset resets the message to default state.
func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
}

// ProtoMessage marks this as a protobuf message.
func (x *RegisterRequest) ProtoMessage() {}

// AgentCapabilities describes what the agent can do.
type AgentCapabilities struct {
	CanUseNamespaces bool     `json:"can_use_namespaces,omitempty"`
	AllowedUsers     []string `json:"allowed_users,omitempty"`
	DiskSpaceBytes   int64    `json:"disk_space_bytes,omitempty"`
	MemoryBytes      int64    `json:"memory_bytes,omitempty"`
}

func (x *AgentCapabilities) GetCanUseNamespaces() bool {
	if x != nil {
		return x.CanUseNamespaces
	}
	return false
}

func (x *AgentCapabilities) GetAllowedUsers() []string {
	if x != nil {
		return x.AllowedUsers
	}
	return nil
}

func (x *AgentCapabilities) GetDiskSpaceBytes() int64 {
	if x != nil {
		return x.DiskSpaceBytes
	}
	return 0
}

func (x *AgentCapabilities) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *AgentCapabilities) Reset()        { *x = AgentCapabilities{} }
func (x *AgentCapabilities) ProtoMessage() {}

// RegisterResponse is returned after successful registration.
type RegisterResponse struct {
	Success       bool   `json:"success,omitempty"`
	Error         string `json:"error,omitempty"`
	Certificate   []byte `json:"certificate,omitempty"`
	CaCertificate []byte `json:"ca_certificate,omitempty"`
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RegisterResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *RegisterResponse) GetCaCertificate() []byte {
	if x != nil {
		return x.CaCertificate
	}
	return nil
}

func (x *RegisterResponse) Reset()        { *x = RegisterResponse{} }
func (x *RegisterResponse) ProtoMessage() {}

// HeartbeatRequest is sent periodically by agent.
type HeartbeatRequest struct {
	AgentId           string              `json:"agent_id,omitempty"`
	Timestamp         int64               `json:"timestamp,omitempty"`
	Stats             *AgentStats         `json:"stats,omitempty"`
	ActiveDeployments []*DeploymentStatus `json:"active_deployments,omitempty"`
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetStats() *AgentStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *HeartbeatRequest) GetActiveDeployments() []*DeploymentStatus {
	if x != nil {
		return x.ActiveDeployments
	}
	return nil
}

func (x *HeartbeatRequest) Reset()        { *x = HeartbeatRequest{} }
func (x *HeartbeatRequest) ProtoMessage() {}

// AgentStats contains agent resource statistics.
type AgentStats struct {
	CpuPercent        float64 `json:"cpu_percent,omitempty"`
	MemoryPercent     float64 `json:"memory_percent,omitempty"`
	DiskPercent       float64 `json:"disk_percent,omitempty"`
	DiskFreeBytes     int64   `json:"disk_free_bytes,omitempty"`
	ActiveConnections int32   `json:"active_connections,omitempty"`
}

func (x *AgentStats) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *AgentStats) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *AgentStats) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

func (x *AgentStats) GetDiskFreeBytes() int64 {
	if x != nil {
		return x.DiskFreeBytes
	}
	return 0
}

func (x *AgentStats) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *AgentStats) Reset()        { *x = AgentStats{} }
func (x *AgentStats) ProtoMessage() {}

// HeartbeatResponse acknowledges heartbeat.
type HeartbeatResponse struct {
	Ok              bool  `json:"ok,omitempty"`
	ServerTimestamp int64 `json:"server_timestamp,omitempty"`
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

func (x *HeartbeatResponse) Reset()        { *x = HeartbeatResponse{} }
func (x *HeartbeatResponse) ProtoMessage() {}

// AgentMessage is sent from agent to master over the stream.
type AgentMessage struct {
	// Types that are assignable to Message:
	//
	//	*AgentMessage_DeploymentStatus
	//	*AgentMessage_DeploymentLog
	//	*AgentMessage_CommandResult
	//	*AgentMessage_AgentReady
	Message isAgentMessage_Message
}

func (x *AgentMessage) GetDeploymentStatus() *DeploymentStatus {
	if x, ok := x.GetMessage().(*AgentMessage_DeploymentStatus); ok {
		return x.DeploymentStatus
	}
	return nil
}

func (x *AgentMessage) GetDeploymentLog() *DeploymentLog {
	if x, ok := x.GetMessage().(*AgentMessage_DeploymentLog); ok {
		return x.DeploymentLog
	}
	return nil
}

func (x *AgentMessage) GetCommandResult() *CommandResult {
	if x, ok := x.GetMessage().(*AgentMessage_CommandResult); ok {
		return x.CommandResult
	}
	return nil
}

func (x *AgentMessage) GetAgentReady() *AgentReady {
	if x, ok := x.GetMessage().(*AgentMessage_AgentReady); ok {
		return x.AgentReady
	}
	return nil
}

func (x *AgentMessage) GetMessage() isAgentMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AgentMessage) Reset()        { *x = AgentMessage{} }
func (x *AgentMessage) ProtoMessage() {}

type isAgentMessage_Message interface {
	isAgentMessage_Message()
}

type AgentMessage_DeploymentStatus struct {
	DeploymentStatus *DeploymentStatus
}

type AgentMessage_DeploymentLog struct {
	DeploymentLog *DeploymentLog
}

type AgentMessage_CommandResult struct {
	CommandResult *CommandResult
}

type AgentMessage_AgentReady struct {
	AgentReady *AgentReady
}

func (*AgentMessage_DeploymentStatus) isAgentMessage_Message() {}
func (*AgentMessage_DeploymentLog) isAgentMessage_Message()    {}
func (*AgentMessage_CommandResult) isAgentMessage_Message()    {}
func (*AgentMessage_AgentReady) isAgentMessage_Message()       {}

// MasterMessage is sent from master to agent over the stream.
type MasterMessage struct {
	// Types that are assignable to Message:
	//
	//	*MasterMessage_DeployCommand
	//	*MasterMessage_RollbackCommand
	//	*MasterMessage_CancelCommand
	//	*MasterMessage_HealthCheckCommand
	Message isMasterMessage_Message
}

func (x *MasterMessage) GetDeployCommand() *DeployCommand {
	if x, ok := x.GetMessage().(*MasterMessage_DeployCommand); ok {
		return x.DeployCommand
	}
	return nil
}

func (x *MasterMessage) GetRollbackCommand() *RollbackCommand {
	if x, ok := x.GetMessage().(*MasterMessage_RollbackCommand); ok {
		return x.RollbackCommand
	}
	return nil
}

func (x *MasterMessage) GetCancelCommand() *CancelCommand {
	if x, ok := x.GetMessage().(*MasterMessage_CancelCommand); ok {
		return x.CancelCommand
	}
	return nil
}

func (x *MasterMessage) GetHealthCheckCommand() *HealthCheckCommand {
	if x, ok := x.GetMessage().(*MasterMessage_HealthCheckCommand); ok {
		return x.HealthCheckCommand
	}
	return nil
}

func (x *MasterMessage) GetMessage() isMasterMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MasterMessage) Reset()        { *x = MasterMessage{} }
func (x *MasterMessage) ProtoMessage() {}

type isMasterMessage_Message interface {
	isMasterMessage_Message()
}

type MasterMessage_DeployCommand struct {
	DeployCommand *DeployCommand
}

type MasterMessage_RollbackCommand struct {
	RollbackCommand *RollbackCommand
}

type MasterMessage_CancelCommand struct {
	CancelCommand *CancelCommand
}

type MasterMessage_HealthCheckCommand struct {
	HealthCheckCommand *HealthCheckCommand
}

func (*MasterMessage_DeployCommand) isMasterMessage_Message()      {}
func (*MasterMessage_RollbackCommand) isMasterMessage_Message()    {}
func (*MasterMessage_CancelCommand) isMasterMessage_Message()      {}
func (*MasterMessage_HealthCheckCommand) isMasterMessage_Message() {}

// DeployCommand instructs agent to deploy a project.
type DeployCommand struct {
	DeploymentId    string              `json:"deployment_id,omitempty"`
	Project         string              `json:"project,omitempty"`
	Target          string              `json:"target,omitempty"`
	Repository      string              `json:"repository,omitempty"`
	Branch          string              `json:"branch,omitempty"`
	Commit          string              `json:"commit,omitempty"`
	Path            string              `json:"path,omitempty"`
	Settings        *DeploymentSettings `json:"settings,omitempty"`
	EnvVars         map[string]string   `json:"env_vars,omitempty"`
	EnvFileContent  []byte              `json:"env_file_content,omitempty"`
	PreDeployHooks  []string            `json:"pre_deploy_hooks,omitempty"`
	PostDeployHooks []string            `json:"post_deploy_hooks,omitempty"`
	ReloadServices  []*ServiceReload    `json:"reload_services,omitempty"`
}

func (x *DeployCommand) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeployCommand) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *DeployCommand) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *DeployCommand) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *DeployCommand) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *DeployCommand) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *DeployCommand) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeployCommand) GetSettings() *DeploymentSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *DeployCommand) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *DeployCommand) GetEnvFileContent() []byte {
	if x != nil {
		return x.EnvFileContent
	}
	return nil
}

func (x *DeployCommand) GetPreDeployHooks() []string {
	if x != nil {
		return x.PreDeployHooks
	}
	return nil
}

func (x *DeployCommand) GetPostDeployHooks() []string {
	if x != nil {
		return x.PostDeployHooks
	}
	return nil
}

func (x *DeployCommand) GetReloadServices() []*ServiceReload {
	if x != nil {
		return x.ReloadServices
	}
	return nil
}

func (x *DeployCommand) Reset()        { *x = DeployCommand{} }
func (x *DeployCommand) ProtoMessage() {}

// DeploymentSettings contains deployment configuration.
type DeploymentSettings struct {
	Strategy       string   `json:"strategy,omitempty"`
	KeepReleases   int32    `json:"keep_releases,omitempty"`
	SharedDirs     []string `json:"shared_dirs,omitempty"`
	SharedFiles    []string `json:"shared_files,omitempty"`
	WritableDirs   []string `json:"writable_dirs,omitempty"`
	ExecutionUser  string   `json:"execution_user,omitempty"`
	ExecutionGroup string   `json:"execution_group,omitempty"`
	TimeoutSeconds int32    `json:"timeout_seconds,omitempty"`
}

func (x *DeploymentSettings) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *DeploymentSettings) GetKeepReleases() int32 {
	if x != nil {
		return x.KeepReleases
	}
	return 0
}

func (x *DeploymentSettings) GetSharedDirs() []string {
	if x != nil {
		return x.SharedDirs
	}
	return nil
}

func (x *DeploymentSettings) GetSharedFiles() []string {
	if x != nil {
		return x.SharedFiles
	}
	return nil
}

func (x *DeploymentSettings) GetWritableDirs() []string {
	if x != nil {
		return x.WritableDirs
	}
	return nil
}

func (x *DeploymentSettings) GetExecutionUser() string {
	if x != nil {
		return x.ExecutionUser
	}
	return ""
}

func (x *DeploymentSettings) GetExecutionGroup() string {
	if x != nil {
		return x.ExecutionGroup
	}
	return ""
}

func (x *DeploymentSettings) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *DeploymentSettings) Reset()        { *x = DeploymentSettings{} }
func (x *DeploymentSettings) ProtoMessage() {}

// ServiceReload defines a service to reload.
type ServiceReload struct {
	Service string `json:"service,omitempty"`
	Action  string `json:"action,omitempty"`
}

func (x *ServiceReload) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ServiceReload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ServiceReload) Reset()        { *x = ServiceReload{} }
func (x *ServiceReload) ProtoMessage() {}

// RollbackCommand instructs agent to rollback to a previous release.
type RollbackCommand struct {
	DeploymentId   string           `json:"deployment_id,omitempty"`
	Project        string           `json:"project,omitempty"`
	Target         string           `json:"target,omitempty"`
	Path           string           `json:"path,omitempty"`
	ReleaseNumber  int32            `json:"release_number,omitempty"`
	RollbackHooks  []string         `json:"rollback_hooks,omitempty"`
	ReloadServices []*ServiceReload `json:"reload_services,omitempty"`
}

func (x *RollbackCommand) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *RollbackCommand) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *RollbackCommand) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RollbackCommand) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RollbackCommand) GetReleaseNumber() int32 {
	if x != nil {
		return x.ReleaseNumber
	}
	return 0
}

func (x *RollbackCommand) GetRollbackHooks() []string {
	if x != nil {
		return x.RollbackHooks
	}
	return nil
}

func (x *RollbackCommand) GetReloadServices() []*ServiceReload {
	if x != nil {
		return x.ReloadServices
	}
	return nil
}

func (x *RollbackCommand) Reset()        { *x = RollbackCommand{} }
func (x *RollbackCommand) ProtoMessage() {}

// CancelCommand instructs agent to cancel an in-progress deployment.
type CancelCommand struct {
	DeploymentId string `json:"deployment_id,omitempty"`
	Reason       string `json:"reason,omitempty"`
}

func (x *CancelCommand) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *CancelCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CancelCommand) Reset()        { *x = CancelCommand{} }
func (x *CancelCommand) ProtoMessage() {}

// HealthCheckCommand instructs agent to check health.
type HealthCheckCommand struct {
	DeploymentId   string `json:"deployment_id,omitempty"`
	Url            string `json:"url,omitempty"`
	TimeoutSeconds int32  `json:"timeout_seconds,omitempty"`
	Retries        int32  `json:"retries,omitempty"`
}

func (x *HealthCheckCommand) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *HealthCheckCommand) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HealthCheckCommand) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *HealthCheckCommand) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *HealthCheckCommand) Reset()        { *x = HealthCheckCommand{} }
func (x *HealthCheckCommand) ProtoMessage() {}

// DeploymentStatus reports deployment progress.
type DeploymentStatus struct {
	DeploymentId    string          `json:"deployment_id,omitempty"`
	State           DeploymentState `json:"state,omitempty"`
	Message         string          `json:"message,omitempty"`
	Timestamp       int64           `json:"timestamp,omitempty"`
	ProgressPercent int32           `json:"progress_percent,omitempty"`
	CurrentStep     string          `json:"current_step,omitempty"`
	ReleaseNumber   int32           `json:"release_number,omitempty"`
}

func (x *DeploymentStatus) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeploymentStatus) GetState() DeploymentState {
	if x != nil {
		return x.State
	}
	return DeploymentState_DEPLOYMENT_STATE_UNSPECIFIED
}

func (x *DeploymentStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeploymentStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DeploymentStatus) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *DeploymentStatus) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *DeploymentStatus) GetReleaseNumber() int32 {
	if x != nil {
		return x.ReleaseNumber
	}
	return 0
}

func (x *DeploymentStatus) Reset()        { *x = DeploymentStatus{} }
func (x *DeploymentStatus) ProtoMessage() {}

// DeploymentLog streams log output from deployment.
type DeploymentLog struct {
	DeploymentId string   `json:"deployment_id,omitempty"`
	Timestamp    int64    `json:"timestamp,omitempty"`
	Level        LogLevel `json:"level,omitempty"`
	Message      string   `json:"message,omitempty"`
	Source       string   `json:"source,omitempty"`
}

func (x *DeploymentLog) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeploymentLog) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DeploymentLog) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *DeploymentLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeploymentLog) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DeploymentLog) Reset()        { *x = DeploymentLog{} }
func (x *DeploymentLog) ProtoMessage() {}

// CommandResult reports the result of a command execution.
type CommandResult struct {
	DeploymentId string `json:"deployment_id,omitempty"`
	Command      string `json:"command,omitempty"`
	ExitCode     int32  `json:"exit_code,omitempty"`
	Stdout       string `json:"stdout,omitempty"`
	Stderr       string `json:"stderr,omitempty"`
	DurationMs   int64  `json:"duration_ms,omitempty"`
}

func (x *CommandResult) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *CommandResult) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *CommandResult) Reset()        { *x = CommandResult{} }
func (x *CommandResult) ProtoMessage() {}

// AgentReady signals agent is ready for commands.
type AgentReady struct {
	AgentId   string `json:"agent_id,omitempty"`
	Timestamp int64  `json:"timestamp,omitempty"`
}

func (x *AgentReady) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentReady) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AgentReady) Reset()        { *x = AgentReady{} }
func (x *AgentReady) ProtoMessage() {}
