// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeploymentState represents deployment state.
type DeploymentState int32

const (
	DeploymentState_DEPLOYMENT_STATE_UNSPECIFIED  DeploymentState = 0
	DeploymentState_DEPLOYMENT_STATE_PENDING      DeploymentState = 1
	DeploymentState_DEPLOYMENT_STATE_PREPARING    DeploymentState = 2
	DeploymentState_DEPLOYMENT_STATE_CLONING      DeploymentState = 3
	DeploymentState_DEPLOYMENT_STATE_BUILDING     DeploymentState = 4
	DeploymentState_DEPLOYMENT_STATE_DEPLOYING    DeploymentState = 5
	DeploymentState_DEPLOYMENT_STATE_VERIFYING    DeploymentState = 6
	DeploymentState_DEPLOYMENT_STATE_COMPLETED    DeploymentState = 7
	DeploymentState_DEPLOYMENT_STATE_FAILED       DeploymentState = 8
	DeploymentState_DEPLOYMENT_STATE_CANCELLED    DeploymentState = 9
	DeploymentState_DEPLOYMENT_STATE_ROLLING_BACK DeploymentState = 10
)

// Enum value maps for DeploymentState.
var (
	DeploymentState_name = map[int32]string{
		0:  "DEPLOYMENT_STATE_UNSPECIFIED",
		1:  "DEPLOYMENT_STATE_PENDING",
		2:  "DEPLOYMENT_STATE_PREPARING",
		3:  "DEPLOYMENT_STATE_CLONING",
		4:  "DEPLOYMENT_STATE_BUILDING",
		5:  "DEPLOYMENT_STATE_DEPLOYING",
		6:  "DEPLOYMENT_STATE_VERIFYING",
		7:  "DEPLOYMENT_STATE_COMPLETED",
		8:  "DEPLOYMENT_STATE_FAILED",
		9:  "DEPLOYMENT_STATE_CANCELLED",
		10: "DEPLOYMENT_STATE_ROLLING_BACK",
	}
	DeploymentState_value = map[string]int32{
		"DEPLOYMENT_STATE_UNSPECIFIED":  0,
		"DEPLOYMENT_STATE_PENDING":      1,
		"DEPLOYMENT_STATE_PREPARING":    2,
		"DEPLOYMENT_STATE_CLONING":      3,
		"DEPLOYMENT_STATE_BUILDING":     4,
		"DEPLOYMENT_STATE_DEPLOYING":    5,
		"DEPLOYMENT_STATE_VERIFYING":    6,
		"DEPLOYMENT_STATE_COMPLETED":    7,
		"DEPLOYMENT_STATE_FAILED":       8,
		"DEPLOYMENT_STATE_CANCELLED":    9,
		"DEPLOYMENT_STATE_ROLLING_BACK": 10,
	}
)

func (x DeploymentState) Enum() *DeploymentState {
	p := new(DeploymentState)
	*p = x
	return p
}

func (x DeploymentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_agent_proto_enumTypes[0].Descriptor()
}

func (DeploymentState) Type() protoreflect.EnumType {
	return &file_api_proto_agent_proto_enumTypes[0]
}

func (x DeploymentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeploymentState.Descriptor instead.
func (DeploymentState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{0}
}

// LogLevel represents log severity.
type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARN        LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARN",
		4: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARN":        3,
		"LOG_LEVEL_ERROR":       4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_agent_proto_enumTypes[1].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_api_proto_agent_proto_enumTypes[1]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{1}
}

// RegisterRequest is sent by agent to register with master.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Capabilities  *AgentCapabilities     `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRequest) GetCapabilities() *AgentCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// AgentCapabilities describes what the agent can do.
type AgentCapabilities struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CanUseNamespaces bool                   `protobuf:"varint,1,opt,name=can_use_namespaces,json=canUseNamespaces,proto3" json:"can_use_namespaces,omitempty"`
	AllowedUsers     []string               `protobuf:"bytes,2,rep,name=allowed_users,json=allowedUsers,proto3" json:"allowed_users,omitempty"`
	DiskSpaceBytes   int64                  `protobuf:"varint,3,opt,name=disk_space_bytes,json=diskSpaceBytes,proto3" json:"disk_space_bytes,omitempty"`
	MemoryBytes      int64                  `protobuf:"varint,4,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentCapabilities) Reset() {
	*x = AgentCapabilities{}
	mi := &file_api_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCapabilities) ProtoMessage() {}

func (x *AgentCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCapabilities.ProtoReflect.Descriptor instead.
func (*AgentCapabilities) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentCapabilities) GetCanUseNamespaces() bool {
	if x != nil {
		return x.CanUseNamespaces
	}
	return false
}

func (x *AgentCapabilities) GetAllowedUsers() []string {
	if x != nil {
		return x.AllowedUsers
	}
	return nil
}

func (x *AgentCapabilities) GetDiskSpaceBytes() int64 {
	if x != nil {
		return x.DiskSpaceBytes
	}
	return 0
}

func (x *AgentCapabilities) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

// RegisterResponse is returned after successful registration.
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Certificate   []byte                 `protobuf:"bytes,3,opt,name=certificate,proto3" json:"certificate,omitempty"`                          // mTLS certificate for future connections
	CaCertificate []byte                 `protobuf:"bytes,4,opt,name=ca_certificate,json=caCertificate,proto3" json:"ca_certificate,omitempty"` // CA certificate for verification
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RegisterResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *RegisterResponse) GetCaCertificate() []byte {
	if x != nil {
		return x.CaCertificate
	}
	return nil
}

// HeartbeatRequest is sent periodically by agent.
type HeartbeatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentId           string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp         int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Stats             *AgentStats            `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	ActiveDeployments []*DeploymentStatus    `protobuf:"bytes,4,rep,name=active_deployments,json=activeDeployments,proto3" json:"active_deployments,omitempty"`
	Version           string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"` // Current agent version
	Os                string                 `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`           // Agent OS (linux, darwin, windows)
	Arch              string                 `protobuf:"bytes,7,opt,name=arch,proto3" json:"arch,omitempty"`       // Agent architecture (amd64, arm64)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetStats() *AgentStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *HeartbeatRequest) GetActiveDeployments() []*DeploymentStatus {
	if x != nil {
		return x.ActiveDeployments
	}
	return nil
}

func (x *HeartbeatRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HeartbeatRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HeartbeatRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

// AgentStats contains agent resource statistics.
type AgentStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent        float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent     float64                `protobuf:"fixed64,2,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	DiskPercent       float64                `protobuf:"fixed64,3,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	DiskFreeBytes     int64                  `protobuf:"varint,4,opt,name=disk_free_bytes,json=diskFreeBytes,proto3" json:"disk_free_bytes,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,5,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AgentStats) Reset() {
	*x = AgentStats{}
	mi := &file_api_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStats) ProtoMessage() {}

func (x *AgentStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStats.ProtoReflect.Descriptor instead.
func (*AgentStats) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentStats) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *AgentStats) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *AgentStats) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

func (x *AgentStats) GetDiskFreeBytes() int64 {
	if x != nil {
		return x.DiskFreeBytes
	}
	return 0
}

func (x *AgentStats) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

// HeartbeatResponse acknowledges heartbeat.
type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ok              bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ServerTimestamp int64                  `protobuf:"varint,2,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	UpdateAvailable *UpdateNotification    `protobuf:"bytes,3,opt,name=update_available,json=updateAvailable,proto3" json:"update_available,omitempty"` // Present if agent should update
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

func (x *HeartbeatResponse) GetUpdateAvailable() *UpdateNotification {
	if x != nil {
		return x.UpdateAvailable
	}
	return nil
}

// UpdateNotification tells the agent about an available update.
type UpdateNotification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Version        string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                                     // New version to update to
	DownloadUrl    string                 `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`          // URL to download the binary from
	ChecksumSha256 string                 `protobuf:"bytes,3,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"` // SHA256 checksum for verification
	SizeBytes      int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`               // Expected file size
	Force          bool                   `protobuf:"varint,5,opt,name=force,proto3" json:"force,omitempty"`                                        // If true, ignore update policy and update immediately
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateNotification) Reset() {
	*x = UpdateNotification{}
	mi := &file_api_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotification) ProtoMessage() {}

func (x *UpdateNotification) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotification.ProtoReflect.Descriptor instead.
func (*UpdateNotification) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateNotification) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateNotification) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *UpdateNotification) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

func (x *UpdateNotification) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *UpdateNotification) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// AgentMessage is sent from agent to master over the stream.
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*AgentMessage_DeploymentStatus
	//	*AgentMessage_DeploymentLog
	//	*AgentMessage_CommandResult
	//	*AgentMessage_AgentReady
	//	*AgentMessage_UpdateResult
	//	*AgentMessage_HealthCheckResult
	Message       isAgentMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_api_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *AgentMessage) GetMessage() isAgentMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AgentMessage) GetDeploymentStatus() *DeploymentStatus {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_DeploymentStatus); ok {
			return x.DeploymentStatus
		}
	}
	return nil
}

func (x *AgentMessage) GetDeploymentLog() *DeploymentLog {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_DeploymentLog); ok {
			return x.DeploymentLog
		}
	}
	return nil
}

func (x *AgentMessage) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

func (x *AgentMessage) GetAgentReady() *AgentReady {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_AgentReady); ok {
			return x.AgentReady
		}
	}
	return nil
}

func (x *AgentMessage) GetUpdateResult() *UpdateResult {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_UpdateResult); ok {
			return x.UpdateResult
		}
	}
	return nil
}

func (x *AgentMessage) GetHealthCheckResult() *HealthCheckResult {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_HealthCheckResult); ok {
			return x.HealthCheckResult
		}
	}
	return nil
}

type isAgentMessage_Message interface {
	isAgentMessage_Message()
}

type AgentMessage_DeploymentStatus struct {
	DeploymentStatus *DeploymentStatus `protobuf:"bytes,1,opt,name=deployment_status,json=deploymentStatus,proto3,oneof"`
}

type AgentMessage_DeploymentLog struct {
	DeploymentLog *DeploymentLog `protobuf:"bytes,2,opt,name=deployment_log,json=deploymentLog,proto3,oneof"`
}

type AgentMessage_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,3,opt,name=command_result,json=commandResult,proto3,oneof"`
}

type AgentMessage_AgentReady struct {
	AgentReady *AgentReady `protobuf:"bytes,4,opt,name=agent_ready,json=agentReady,proto3,oneof"`
}

type AgentMessage_UpdateResult struct {
	UpdateResult *UpdateResult `protobuf:"bytes,5,opt,name=update_result,json=updateResult,proto3,oneof"`
}

type AgentMessage_HealthCheckResult struct {
	HealthCheckResult *HealthCheckResult `protobuf:"bytes,6,opt,name=health_check_result,json=healthCheckResult,proto3,oneof"`
}

func (*AgentMessage_DeploymentStatus) isAgentMessage_Message() {}

func (*AgentMessage_DeploymentLog) isAgentMessage_Message() {}

func (*AgentMessage_CommandResult) isAgentMessage_Message() {}

func (*AgentMessage_AgentReady) isAgentMessage_Message() {}

func (*AgentMessage_UpdateResult) isAgentMessage_Message() {}

func (*AgentMessage_HealthCheckResult) isAgentMessage_Message() {}

// UpdateResult reports the result of an agent update.
type UpdateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromVersion   string                 `protobuf:"bytes,1,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"`
	ToVersion     string                 `protobuf:"bytes,2,opt,name=to_version,json=toVersion,proto3" json:"to_version,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	RolledBack    bool                   `protobuf:"varint,5,opt,name=rolled_back,json=rolledBack,proto3" json:"rolled_back,omitempty"` // True if update failed and agent rolled back
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResult) Reset() {
	*x = UpdateResult{}
	mi := &file_api_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResult) ProtoMessage() {}

func (x *UpdateResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResult.ProtoReflect.Descriptor instead.
func (*UpdateResult) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateResult) GetFromVersion() string {
	if x != nil {
		return x.FromVersion
	}
	return ""
}

func (x *UpdateResult) GetToVersion() string {
	if x != nil {
		return x.ToVersion
	}
	return ""
}

func (x *UpdateResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateResult) GetRolledBack() bool {
	if x != nil {
		return x.RolledBack
	}
	return false
}

// HealthCheckResult reports the result of a health check.
type HealthCheckResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId    string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Success         bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	StatusCode      int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ResponseTimeMs  int64                  `protobuf:"varint,4,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	Error           string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	RetryCount      int32                  `protobuf:"varint,6,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`                // How many retries were attempted
	TriggerRollback bool                   `protobuf:"varint,7,opt,name=trigger_rollback,json=triggerRollback,proto3" json:"trigger_rollback,omitempty"` // Whether to trigger automatic rollback
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthCheckResult) Reset() {
	*x = HealthCheckResult{}
	mi := &file_api_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResult) ProtoMessage() {}

func (x *HealthCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResult.ProtoReflect.Descriptor instead.
func (*HealthCheckResult) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckResult) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *HealthCheckResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HealthCheckResult) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HealthCheckResult) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *HealthCheckResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HealthCheckResult) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *HealthCheckResult) GetTriggerRollback() bool {
	if x != nil {
		return x.TriggerRollback
	}
	return false
}

// MasterMessage is sent from master to agent over the stream.
type MasterMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*MasterMessage_DeployCommand
	//	*MasterMessage_RollbackCommand
	//	*MasterMessage_CancelCommand
	//	*MasterMessage_HealthCheckCommand
	//	*MasterMessage_UpdateCommand
	Message       isMasterMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterMessage) Reset() {
	*x = MasterMessage{}
	mi := &file_api_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterMessage) ProtoMessage() {}

func (x *MasterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterMessage.ProtoReflect.Descriptor instead.
func (*MasterMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *MasterMessage) GetMessage() isMasterMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MasterMessage) GetDeployCommand() *DeployCommand {
	if x != nil {
		if x, ok := x.Message.(*MasterMessage_DeployCommand); ok {
			return x.DeployCommand
		}
	}
	return nil
}

func (x *MasterMessage) GetRollbackCommand() *RollbackCommand {
	if x != nil {
		if x, ok := x.Message.(*MasterMessage_RollbackCommand); ok {
			return x.RollbackCommand
		}
	}
	return nil
}

func (x *MasterMessage) GetCancelCommand() *CancelCommand {
	if x != nil {
		if x, ok := x.Message.(*MasterMessage_CancelCommand); ok {
			return x.CancelCommand
		}
	}
	return nil
}

func (x *MasterMessage) GetHealthCheckCommand() *HealthCheckCommand {
	if x != nil {
		if x, ok := x.Message.(*MasterMessage_HealthCheckCommand); ok {
			return x.HealthCheckCommand
		}
	}
	return nil
}

func (x *MasterMessage) GetUpdateCommand() *UpdateCommand {
	if x != nil {
		if x, ok := x.Message.(*MasterMessage_UpdateCommand); ok {
			return x.UpdateCommand
		}
	}
	return nil
}

type isMasterMessage_Message interface {
	isMasterMessage_Message()
}

type MasterMessage_DeployCommand struct {
	DeployCommand *DeployCommand `protobuf:"bytes,1,opt,name=deploy_command,json=deployCommand,proto3,oneof"`
}

type MasterMessage_RollbackCommand struct {
	RollbackCommand *RollbackCommand `protobuf:"bytes,2,opt,name=rollback_command,json=rollbackCommand,proto3,oneof"`
}

type MasterMessage_CancelCommand struct {
	CancelCommand *CancelCommand `protobuf:"bytes,3,opt,name=cancel_command,json=cancelCommand,proto3,oneof"`
}

type MasterMessage_HealthCheckCommand struct {
	HealthCheckCommand *HealthCheckCommand `protobuf:"bytes,4,opt,name=health_check_command,json=healthCheckCommand,proto3,oneof"`
}

type MasterMessage_UpdateCommand struct {
	UpdateCommand *UpdateCommand `protobuf:"bytes,5,opt,name=update_command,json=updateCommand,proto3,oneof"`
}

func (*MasterMessage_DeployCommand) isMasterMessage_Message() {}

func (*MasterMessage_RollbackCommand) isMasterMessage_Message() {}

func (*MasterMessage_CancelCommand) isMasterMessage_Message() {}

func (*MasterMessage_HealthCheckCommand) isMasterMessage_Message() {}

func (*MasterMessage_UpdateCommand) isMasterMessage_Message() {}

// UpdateCommand instructs agent to update itself.
type UpdateCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Version        string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                                     // Version to update to
	DownloadUrl    string                 `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`          // URL to download the binary from
	ChecksumSha256 string                 `protobuf:"bytes,3,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"` // SHA256 checksum for verification
	SizeBytes      int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`               // Expected file size
	Force          bool                   `protobuf:"varint,5,opt,name=force,proto3" json:"force,omitempty"`                                        // If true, restart even if health check fails
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateCommand) Reset() {
	*x = UpdateCommand{}
	mi := &file_api_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommand) ProtoMessage() {}

func (x *UpdateCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommand.ProtoReflect.Descriptor instead.
func (*UpdateCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateCommand) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateCommand) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *UpdateCommand) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

func (x *UpdateCommand) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *UpdateCommand) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// DeployCommand instructs agent to deploy a project.
type DeployCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId    string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Project         string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Target          string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Repository      string                 `protobuf:"bytes,4,opt,name=repository,proto3" json:"repository,omitempty"`
	Branch          string                 `protobuf:"bytes,5,opt,name=branch,proto3" json:"branch,omitempty"`
	Commit          string                 `protobuf:"bytes,6,opt,name=commit,proto3" json:"commit,omitempty"`
	Path            string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	Settings        *DeploymentSettings    `protobuf:"bytes,8,opt,name=settings,proto3" json:"settings,omitempty"`
	EnvVars         map[string]string      `protobuf:"bytes,9,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EnvFileContent  []byte                 `protobuf:"bytes,10,opt,name=env_file_content,json=envFileContent,proto3" json:"env_file_content,omitempty"`
	PreDeployHooks  []string               `protobuf:"bytes,11,rep,name=pre_deploy_hooks,json=preDeployHooks,proto3" json:"pre_deploy_hooks,omitempty"`
	PostDeployHooks []string               `protobuf:"bytes,12,rep,name=post_deploy_hooks,json=postDeployHooks,proto3" json:"post_deploy_hooks,omitempty"`
	ReloadServices  []*ServiceReload       `protobuf:"bytes,13,rep,name=reload_services,json=reloadServices,proto3" json:"reload_services,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeployCommand) Reset() {
	*x = DeployCommand{}
	mi := &file_api_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployCommand) ProtoMessage() {}

func (x *DeployCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployCommand.ProtoReflect.Descriptor instead.
func (*DeployCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *DeployCommand) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeployCommand) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *DeployCommand) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *DeployCommand) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *DeployCommand) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *DeployCommand) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *DeployCommand) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeployCommand) GetSettings() *DeploymentSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *DeployCommand) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *DeployCommand) GetEnvFileContent() []byte {
	if x != nil {
		return x.EnvFileContent
	}
	return nil
}

func (x *DeployCommand) GetPreDeployHooks() []string {
	if x != nil {
		return x.PreDeployHooks
	}
	return nil
}

func (x *DeployCommand) GetPostDeployHooks() []string {
	if x != nil {
		return x.PostDeployHooks
	}
	return nil
}

func (x *DeployCommand) GetReloadServices() []*ServiceReload {
	if x != nil {
		return x.ReloadServices
	}
	return nil
}

// DeploymentSettings contains deployment configuration.
type DeploymentSettings struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Strategy       string                 `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"` // symlink | inplace
	KeepReleases   int32                  `protobuf:"varint,2,opt,name=keep_releases,json=keepReleases,proto3" json:"keep_releases,omitempty"`
	SharedDirs     []string               `protobuf:"bytes,3,rep,name=shared_dirs,json=sharedDirs,proto3" json:"shared_dirs,omitempty"`
	SharedFiles    []string               `protobuf:"bytes,4,rep,name=shared_files,json=sharedFiles,proto3" json:"shared_files,omitempty"`
	WritableDirs   []string               `protobuf:"bytes,5,rep,name=writable_dirs,json=writableDirs,proto3" json:"writable_dirs,omitempty"`
	ExecutionUser  string                 `protobuf:"bytes,6,opt,name=execution_user,json=executionUser,proto3" json:"execution_user,omitempty"`
	ExecutionGroup string                 `protobuf:"bytes,7,opt,name=execution_group,json=executionGroup,proto3" json:"execution_group,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeploymentSettings) Reset() {
	*x = DeploymentSettings{}
	mi := &file_api_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentSettings) ProtoMessage() {}

func (x *DeploymentSettings) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentSettings.ProtoReflect.Descriptor instead.
func (*DeploymentSettings) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *DeploymentSettings) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *DeploymentSettings) GetKeepReleases() int32 {
	if x != nil {
		return x.KeepReleases
	}
	return 0
}

func (x *DeploymentSettings) GetSharedDirs() []string {
	if x != nil {
		return x.SharedDirs
	}
	return nil
}

func (x *DeploymentSettings) GetSharedFiles() []string {
	if x != nil {
		return x.SharedFiles
	}
	return nil
}

func (x *DeploymentSettings) GetWritableDirs() []string {
	if x != nil {
		return x.WritableDirs
	}
	return nil
}

func (x *DeploymentSettings) GetExecutionUser() string {
	if x != nil {
		return x.ExecutionUser
	}
	return ""
}

func (x *DeploymentSettings) GetExecutionGroup() string {
	if x != nil {
		return x.ExecutionGroup
	}
	return ""
}

func (x *DeploymentSettings) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// ServiceReload defines a service to reload.
type ServiceReload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceReload) Reset() {
	*x = ServiceReload{}
	mi := &file_api_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceReload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceReload) ProtoMessage() {}

func (x *ServiceReload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceReload.ProtoReflect.Descriptor instead.
func (*ServiceReload) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ServiceReload) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ServiceReload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// RollbackCommand instructs agent to rollback to a previous release.
type RollbackCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId   string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Project        string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Target         string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Path           string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	ReleaseNumber  int32                  `protobuf:"varint,5,opt,name=release_number,json=releaseNumber,proto3" json:"release_number,omitempty"` // 0 = previous release
	RollbackHooks  []string               `protobuf:"bytes,6,rep,name=rollback_hooks,json=rollbackHooks,proto3" json:"rollback_hooks,omitempty"`
	ReloadServices []*ServiceReload       `protobuf:"bytes,7,rep,name=reload_services,json=reloadServices,proto3" json:"reload_services,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RollbackCommand) Reset() {
	*x = RollbackCommand{}
	mi := &file_api_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackCommand) ProtoMessage() {}

func (x *RollbackCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackCommand.ProtoReflect.Descriptor instead.
func (*RollbackCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *RollbackCommand) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *RollbackCommand) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *RollbackCommand) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RollbackCommand) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RollbackCommand) GetReleaseNumber() int32 {
	if x != nil {
		return x.ReleaseNumber
	}
	return 0
}

func (x *RollbackCommand) GetRollbackHooks() []string {
	if x != nil {
		return x.RollbackHooks
	}
	return nil
}

func (x *RollbackCommand) GetReloadServices() []*ServiceReload {
	if x != nil {
		return x.ReloadServices
	}
	return nil
}

// CancelCommand instructs agent to cancel an in-progress deployment.
type CancelCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelCommand) Reset() {
	*x = CancelCommand{}
	mi := &file_api_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelCommand) ProtoMessage() {}

func (x *CancelCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelCommand.ProtoReflect.Descriptor instead.
func (*CancelCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *CancelCommand) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *CancelCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// HealthCheckCommand instructs agent to check health.
type HealthCheckCommand struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId      string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Url               string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Method            string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"` // HTTP method (GET, POST, etc.)
	TimeoutSeconds    int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Retries           int32                  `protobuf:"varint,5,opt,name=retries,proto3" json:"retries,omitempty"`
	RetryDelaySeconds int32                  `protobuf:"varint,6,opt,name=retry_delay_seconds,json=retryDelaySeconds,proto3" json:"retry_delay_seconds,omitempty"`
	ExpectedStatus    int32                  `protobuf:"varint,7,opt,name=expected_status,json=expectedStatus,proto3" json:"expected_status,omitempty"` // Expected HTTP status code (default 200)
	Headers           map[string]string      `protobuf:"bytes,8,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body              string                 `protobuf:"bytes,9,opt,name=body,proto3" json:"body,omitempty"`                                                // Request body for POST
	BodyContains      string                 `protobuf:"bytes,10,opt,name=body_contains,json=bodyContains,proto3" json:"body_contains,omitempty"`           // Response should contain this string
	TriggerRollback   bool                   `protobuf:"varint,11,opt,name=trigger_rollback,json=triggerRollback,proto3" json:"trigger_rollback,omitempty"` // Whether to trigger rollback on failure
	ReleaseNumber     int32                  `protobuf:"varint,12,opt,name=release_number,json=releaseNumber,proto3" json:"release_number,omitempty"`       // Current release number (for rollback context)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthCheckCommand) Reset() {
	*x = HealthCheckCommand{}
	mi := &file_api_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckCommand) ProtoMessage() {}

func (x *HealthCheckCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckCommand.ProtoReflect.Descriptor instead.
func (*HealthCheckCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{17}
}

func (x *HealthCheckCommand) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *HealthCheckCommand) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HealthCheckCommand) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HealthCheckCommand) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *HealthCheckCommand) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *HealthCheckCommand) GetRetryDelaySeconds() int32 {
	if x != nil {
		return x.RetryDelaySeconds
	}
	return 0
}

func (x *HealthCheckCommand) GetExpectedStatus() int32 {
	if x != nil {
		return x.ExpectedStatus
	}
	return 0
}

func (x *HealthCheckCommand) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HealthCheckCommand) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *HealthCheckCommand) GetBodyContains() string {
	if x != nil {
		return x.BodyContains
	}
	return ""
}

func (x *HealthCheckCommand) GetTriggerRollback() bool {
	if x != nil {
		return x.TriggerRollback
	}
	return false
}

func (x *HealthCheckCommand) GetReleaseNumber() int32 {
	if x != nil {
		return x.ReleaseNumber
	}
	return 0
}

// DeploymentStatus reports deployment progress.
type DeploymentStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId    string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	State           DeploymentState        `protobuf:"varint,2,opt,name=state,proto3,enum=vcdeploy.v1.DeploymentState" json:"state,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp       int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ProgressPercent int32                  `protobuf:"varint,5,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	CurrentStep     string                 `protobuf:"bytes,6,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	ReleaseNumber   int32                  `protobuf:"varint,7,opt,name=release_number,json=releaseNumber,proto3" json:"release_number,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeploymentStatus) Reset() {
	*x = DeploymentStatus{}
	mi := &file_api_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentStatus) ProtoMessage() {}

func (x *DeploymentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentStatus.ProtoReflect.Descriptor instead.
func (*DeploymentStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *DeploymentStatus) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeploymentStatus) GetState() DeploymentState {
	if x != nil {
		return x.State
	}
	return DeploymentState_DEPLOYMENT_STATE_UNSPECIFIED
}

func (x *DeploymentStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeploymentStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DeploymentStatus) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *DeploymentStatus) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *DeploymentStatus) GetReleaseNumber() int32 {
	if x != nil {
		return x.ReleaseNumber
	}
	return 0
}

// DeploymentLog streams log output from deployment.
type DeploymentLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         LogLevel               `protobuf:"varint,3,opt,name=level,proto3,enum=vcdeploy.v1.LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"` // hook name, git, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentLog) Reset() {
	*x = DeploymentLog{}
	mi := &file_api_proto_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentLog) ProtoMessage() {}

func (x *DeploymentLog) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentLog.ProtoReflect.Descriptor instead.
func (*DeploymentLog) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{19}
}

func (x *DeploymentLog) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeploymentLog) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DeploymentLog) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *DeploymentLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeploymentLog) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// CommandResult reports the result of a command execution.
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_api_proto_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{20}
}

func (x *CommandResult) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *CommandResult) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// AgentReady signals agent is ready for commands.
type AgentReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentReady) Reset() {
	*x = AgentReady{}
	mi := &file_api_proto_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentReady) ProtoMessage() {}

func (x *AgentReady) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentReady.ProtoReflect.Descriptor instead.
func (*AgentReady) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{21}
}

func (x *AgentReady) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentReady) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ReauthRequest is sent by agent to re-authenticate using HMAC.
type ReauthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"` // HMAC(agent_id + timestamp + nonce) using shared secret
	Csr           []byte                 `protobuf:"bytes,5,opt,name=csr,proto3" json:"csr,omitempty"`             // Certificate Signing Request for new certificate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReauthRequest) Reset() {
	*x = ReauthRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReauthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReauthRequest) ProtoMessage() {}

func (x *ReauthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReauthRequest.ProtoReflect.Descriptor instead.
func (*ReauthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{22}
}

func (x *ReauthRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReauthRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ReauthRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *ReauthRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ReauthRequest) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

// ReauthResponse contains the new certificate after re-authentication.
type ReauthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   []byte                 `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	CaCertificate []byte                 `protobuf:"bytes,2,opt,name=ca_certificate,json=caCertificate,proto3" json:"ca_certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReauthResponse) Reset() {
	*x = ReauthResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReauthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReauthResponse) ProtoMessage() {}

func (x *ReauthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReauthResponse.ProtoReflect.Descriptor instead.
func (*ReauthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{23}
}

func (x *ReauthResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *ReauthResponse) GetCaCertificate() []byte {
	if x != nil {
		return x.CaCertificate
	}
	return nil
}

// StreamRepoRequest requests a repository archive stream.
type StreamRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	RepoUrl       string                 `protobuf:"bytes,2,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Ref           string                 `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"` // Branch, tag, or commit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRepoRequest) Reset() {
	*x = StreamRepoRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRepoRequest) ProtoMessage() {}

func (x *StreamRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRepoRequest.ProtoReflect.Descriptor instead.
func (*StreamRepoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{24}
}

func (x *StreamRepoRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *StreamRepoRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *StreamRepoRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

// RepoChunk is a chunk of a repository archive stream.
type RepoChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Checksum      string                 `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`                     // SHA256 checksum, only in last chunk
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"` // Total archive size in bytes
	IsLast        bool                   `protobuf:"varint,4,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoChunk) Reset() {
	*x = RepoChunk{}
	mi := &file_api_proto_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoChunk) ProtoMessage() {}

func (x *RepoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoChunk.ProtoReflect.Descriptor instead.
func (*RepoChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{25}
}

func (x *RepoChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RepoChunk) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *RepoChunk) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *RepoChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

var File_api_proto_agent_proto protoreflect.FileDescriptor

const file_api_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/agent.proto\x12\vvcdeploy.v1\"\x9f\x02\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12@\n" +
	"\x06labels\x18\x04 \x03(\v2(.vcdeploy.v1.RegisterRequest.LabelsEntryR\x06labels\x12B\n" +
	"\fcapabilities\x18\x05 \x01(\v2\x1e.vcdeploy.v1.AgentCapabilitiesR\fcapabilities\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x01\n" +
	"\x11AgentCapabilities\x12,\n" +
	"\x12can_use_namespaces\x18\x01 \x01(\bR\x10canUseNamespaces\x12#\n" +
	"\rallowed_users\x18\x02 \x03(\tR\fallowedUsers\x12(\n" +
	"\x10disk_space_bytes\x18\x03 \x01(\x03R\x0ediskSpaceBytes\x12!\n" +
	"\fmemory_bytes\x18\x04 \x01(\x03R\vmemoryBytes\"\x8b\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12 \n" +
	"\vcertificate\x18\x03 \x01(\fR\vcertificate\x12%\n" +
	"\x0eca_certificate\x18\x04 \x01(\fR\rcaCertificate\"\x86\x02\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12-\n" +
	"\x05stats\x18\x03 \x01(\v2\x17.vcdeploy.v1.AgentStatsR\x05stats\x12L\n" +
	"\x12active_deployments\x18\x04 \x03(\v2\x1d.vcdeploy.v1.DeploymentStatusR\x11activeDeployments\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\a \x01(\tR\x04arch\"\xce\x01\n" +
	"\n" +
	"AgentStats\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x02 \x01(\x01R\rmemoryPercent\x12!\n" +
	"\fdisk_percent\x18\x03 \x01(\x01R\vdiskPercent\x12&\n" +
	"\x0fdisk_free_bytes\x18\x04 \x01(\x03R\rdiskFreeBytes\x12-\n" +
	"\x12active_connections\x18\x05 \x01(\x05R\x11activeConnections\"\x9a\x01\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12)\n" +
	"\x10server_timestamp\x18\x02 \x01(\x03R\x0fserverTimestamp\x12J\n" +
	"\x10update_available\x18\x03 \x01(\v2\x1f.vcdeploy.v1.UpdateNotificationR\x0fupdateAvailable\"\xaf\x01\n" +
	"\x12UpdateNotification\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\x12'\n" +
	"\x0fchecksum_sha256\x18\x03 \x01(\tR\x0echecksumSha256\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x14\n" +
	"\x05force\x18\x05 \x01(\bR\x05force\"\xc1\x03\n" +
	"\fAgentMessage\x12L\n" +
	"\x11deployment_status\x18\x01 \x01(\v2\x1d.vcdeploy.v1.DeploymentStatusH\x00R\x10deploymentStatus\x12C\n" +
	"\x0edeployment_log\x18\x02 \x01(\v2\x1a.vcdeploy.v1.DeploymentLogH\x00R\rdeploymentLog\x12C\n" +
	"\x0ecommand_result\x18\x03 \x01(\v2\x1a.vcdeploy.v1.CommandResultH\x00R\rcommandResult\x12:\n" +
	"\vagent_ready\x18\x04 \x01(\v2\x17.vcdeploy.v1.AgentReadyH\x00R\n" +
	"agentReady\x12@\n" +
	"\rupdate_result\x18\x05 \x01(\v2\x19.vcdeploy.v1.UpdateResultH\x00R\fupdateResult\x12P\n" +
	"\x13health_check_result\x18\x06 \x01(\v2\x1e.vcdeploy.v1.HealthCheckResultH\x00R\x11healthCheckResultB\t\n" +
	"\amessage\"\xa1\x01\n" +
	"\fUpdateResult\x12!\n" +
	"\ffrom_version\x18\x01 \x01(\tR\vfromVersion\x12\x1d\n" +
	"\n" +
	"to_version\x18\x02 \x01(\tR\ttoVersion\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1f\n" +
	"\vrolled_back\x18\x05 \x01(\bR\n" +
	"rolledBack\"\xff\x01\n" +
	"\x11HealthCheckResult\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\x12(\n" +
	"\x10response_time_ms\x18\x04 \x01(\x03R\x0eresponseTimeMs\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1f\n" +
	"\vretry_count\x18\x06 \x01(\x05R\n" +
	"retryCount\x12)\n" +
	"\x10trigger_rollback\x18\a \x01(\bR\x0ftriggerRollback\"\x89\x03\n" +
	"\rMasterMessage\x12C\n" +
	"\x0edeploy_command\x18\x01 \x01(\v2\x1a.vcdeploy.v1.DeployCommandH\x00R\rdeployCommand\x12I\n" +
	"\x10rollback_command\x18\x02 \x01(\v2\x1c.vcdeploy.v1.RollbackCommandH\x00R\x0frollbackCommand\x12C\n" +
	"\x0ecancel_command\x18\x03 \x01(\v2\x1a.vcdeploy.v1.CancelCommandH\x00R\rcancelCommand\x12S\n" +
	"\x14health_check_command\x18\x04 \x01(\v2\x1f.vcdeploy.v1.HealthCheckCommandH\x00R\x12healthCheckCommand\x12C\n" +
	"\x0eupdate_command\x18\x05 \x01(\v2\x1a.vcdeploy.v1.UpdateCommandH\x00R\rupdateCommandB\t\n" +
	"\amessage\"\xaa\x01\n" +
	"\rUpdateCommand\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\x12'\n" +
	"\x0fchecksum_sha256\x18\x03 \x01(\tR\x0echecksumSha256\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x14\n" +
	"\x05force\x18\x05 \x01(\bR\x05force\"\xcc\x04\n" +
	"\rDeployCommand\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x1e\n" +
	"\n" +
	"repository\x18\x04 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06branch\x18\x05 \x01(\tR\x06branch\x12\x16\n" +
	"\x06commit\x18\x06 \x01(\tR\x06commit\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12;\n" +
	"\bsettings\x18\b \x01(\v2\x1f.vcdeploy.v1.DeploymentSettingsR\bsettings\x12B\n" +
	"\benv_vars\x18\t \x03(\v2'.vcdeploy.v1.DeployCommand.EnvVarsEntryR\aenvVars\x12(\n" +
	"\x10env_file_content\x18\n" +
	" \x01(\fR\x0eenvFileContent\x12(\n" +
	"\x10pre_deploy_hooks\x18\v \x03(\tR\x0epreDeployHooks\x12*\n" +
	"\x11post_deploy_hooks\x18\f \x03(\tR\x0fpostDeployHooks\x12C\n" +
	"\x0freload_services\x18\r \x03(\v2\x1a.vcdeploy.v1.ServiceReloadR\x0ereloadServices\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x02\n" +
	"\x12DeploymentSettings\x12\x1a\n" +
	"\bstrategy\x18\x01 \x01(\tR\bstrategy\x12#\n" +
	"\rkeep_releases\x18\x02 \x01(\x05R\fkeepReleases\x12\x1f\n" +
	"\vshared_dirs\x18\x03 \x03(\tR\n" +
	"sharedDirs\x12!\n" +
	"\fshared_files\x18\x04 \x03(\tR\vsharedFiles\x12#\n" +
	"\rwritable_dirs\x18\x05 \x03(\tR\fwritableDirs\x12%\n" +
	"\x0eexecution_user\x18\x06 \x01(\tR\rexecutionUser\x12'\n" +
	"\x0fexecution_group\x18\a \x01(\tR\x0eexecutionGroup\x12'\n" +
	"\x0ftimeout_seconds\x18\b \x01(\x05R\x0etimeoutSeconds\"A\n" +
	"\rServiceReload\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"\x8f\x02\n" +
	"\x0fRollbackCommand\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12%\n" +
	"\x0erelease_number\x18\x05 \x01(\x05R\rreleaseNumber\x12%\n" +
	"\x0erollback_hooks\x18\x06 \x03(\tR\rrollbackHooks\x12C\n" +
	"\x0freload_services\x18\a \x03(\v2\x1a.vcdeploy.v1.ServiceReloadR\x0ereloadServices\"L\n" +
	"\rCancelCommand\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x8e\x04\n" +
	"\x12HealthCheckCommand\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x12\x18\n" +
	"\aretries\x18\x05 \x01(\x05R\aretries\x12.\n" +
	"\x13retry_delay_seconds\x18\x06 \x01(\x05R\x11retryDelaySeconds\x12'\n" +
	"\x0fexpected_status\x18\a \x01(\x05R\x0eexpectedStatus\x12F\n" +
	"\aheaders\x18\b \x03(\v2,.vcdeploy.v1.HealthCheckCommand.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\t \x01(\tR\x04body\x12#\n" +
	"\rbody_contains\x18\n" +
	" \x01(\tR\fbodyContains\x12)\n" +
	"\x10trigger_rollback\x18\v \x01(\bR\x0ftriggerRollback\x12%\n" +
	"\x0erelease_number\x18\f \x01(\x05R\rreleaseNumber\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x02\n" +
	"\x10DeploymentStatus\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x122\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1c.vcdeploy.v1.DeploymentStateR\x05state\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12)\n" +
	"\x10progress_percent\x18\x05 \x01(\x05R\x0fprogressPercent\x12!\n" +
	"\fcurrent_step\x18\x06 \x01(\tR\vcurrentStep\x12%\n" +
	"\x0erelease_number\x18\a \x01(\x05R\rreleaseNumber\"\xb1\x01\n" +
	"\rDeploymentLog\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12+\n" +
	"\x05level\x18\x03 \x01(\x0e2\x15.vcdeploy.v1.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"\xbc\x01\n" +
	"\rCommandResult\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\tR\x06stderr\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\"E\n" +
	"\n" +
	"AgentReady\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\x8e\x01\n" +
	"\rReauthRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12\x10\n" +
	"\x03csr\x18\x05 \x01(\fR\x03csr\"Y\n" +
	"\x0eReauthResponse\x12 \n" +
	"\vcertificate\x18\x01 \x01(\fR\vcertificate\x12%\n" +
	"\x0eca_certificate\x18\x02 \x01(\fR\rcaCertificate\"e\n" +
	"\x11StreamRepoRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x19\n" +
	"\brepo_url\x18\x02 \x01(\tR\arepoUrl\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\"s\n" +
	"\tRepoChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\tR\bchecksum\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\x12\x17\n" +
	"\ais_last\x18\x04 \x01(\bR\x06isLast*\xee\x02\n" +
	"\x0fDeploymentState\x12 \n" +
	"\x1cDEPLOYMENT_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DEPLOYMENT_STATE_PENDING\x10\x01\x12\x1e\n" +
	"\x1aDEPLOYMENT_STATE_PREPARING\x10\x02\x12\x1c\n" +
	"\x18DEPLOYMENT_STATE_CLONING\x10\x03\x12\x1d\n" +
	"\x19DEPLOYMENT_STATE_BUILDING\x10\x04\x12\x1e\n" +
	"\x1aDEPLOYMENT_STATE_DEPLOYING\x10\x05\x12\x1e\n" +
	"\x1aDEPLOYMENT_STATE_VERIFYING\x10\x06\x12\x1e\n" +
	"\x1aDEPLOYMENT_STATE_COMPLETED\x10\a\x12\x1b\n" +
	"\x17DEPLOYMENT_STATE_FAILED\x10\b\x12\x1e\n" +
	"\x1aDEPLOYMENT_STATE_CANCELLED\x10\t\x12!\n" +
	"\x1dDEPLOYMENT_STATE_ROLLING_BACK\x10\n" +
	"*w\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x042\x83\x03\n" +
	"\fAgentService\x12G\n" +
	"\bRegister\x12\x1c.vcdeploy.v1.RegisterRequest\x1a\x1d.vcdeploy.v1.RegisterResponse\x12D\n" +
	"\aConnect\x12\x19.vcdeploy.v1.AgentMessage\x1a\x1a.vcdeploy.v1.MasterMessage(\x010\x01\x12J\n" +
	"\tHeartbeat\x12\x1d.vcdeploy.v1.HeartbeatRequest\x1a\x1e.vcdeploy.v1.HeartbeatResponse\x12I\n" +
	"\x0eReauthenticate\x12\x1a.vcdeploy.v1.ReauthRequest\x1a\x1b.vcdeploy.v1.ReauthResponse\x12M\n" +
	"\x11StreamRepoArchive\x12\x1e.vcdeploy.v1.StreamRepoRequest\x1a\x16.vcdeploy.v1.RepoChunk0\x01B/Z-github.com/BlackOrder/vcdeploy/internal/protob\x06proto3"

var (
	file_api_proto_agent_proto_rawDescOnce sync.Once
	file_api_proto_agent_proto_rawDescData []byte
)

func file_api_proto_agent_proto_rawDescGZIP() []byte {
	file_api_proto_agent_proto_rawDescOnce.Do(func() {
		file_api_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agent_proto_rawDesc), len(file_api_proto_agent_proto_rawDesc)))
	})
	return file_api_proto_agent_proto_rawDescData
}

var file_api_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_api_proto_agent_proto_goTypes = []any{
	(DeploymentState)(0),       // 0: vcdeploy.v1.DeploymentState
	(LogLevel)(0),              // 1: vcdeploy.v1.LogLevel
	(*RegisterRequest)(nil),    // 2: vcdeploy.v1.RegisterRequest
	(*AgentCapabilities)(nil),  // 3: vcdeploy.v1.AgentCapabilities
	(*RegisterResponse)(nil),   // 4: vcdeploy.v1.RegisterResponse
	(*HeartbeatRequest)(nil),   // 5: vcdeploy.v1.HeartbeatRequest
	(*AgentStats)(nil),         // 6: vcdeploy.v1.AgentStats
	(*HeartbeatResponse)(nil),  // 7: vcdeploy.v1.HeartbeatResponse
	(*UpdateNotification)(nil), // 8: vcdeploy.v1.UpdateNotification
	(*AgentMessage)(nil),       // 9: vcdeploy.v1.AgentMessage
	(*UpdateResult)(nil),       // 10: vcdeploy.v1.UpdateResult
	(*HealthCheckResult)(nil),  // 11: vcdeploy.v1.HealthCheckResult
	(*MasterMessage)(nil),      // 12: vcdeploy.v1.MasterMessage
	(*UpdateCommand)(nil),      // 13: vcdeploy.v1.UpdateCommand
	(*DeployCommand)(nil),      // 14: vcdeploy.v1.DeployCommand
	(*DeploymentSettings)(nil), // 15: vcdeploy.v1.DeploymentSettings
	(*ServiceReload)(nil),      // 16: vcdeploy.v1.ServiceReload
	(*RollbackCommand)(nil),    // 17: vcdeploy.v1.RollbackCommand
	(*CancelCommand)(nil),      // 18: vcdeploy.v1.CancelCommand
	(*HealthCheckCommand)(nil), // 19: vcdeploy.v1.HealthCheckCommand
	(*DeploymentStatus)(nil),   // 20: vcdeploy.v1.DeploymentStatus
	(*DeploymentLog)(nil),      // 21: vcdeploy.v1.DeploymentLog
	(*CommandResult)(nil),      // 22: vcdeploy.v1.CommandResult
	(*AgentReady)(nil),         // 23: vcdeploy.v1.AgentReady
	(*ReauthRequest)(nil),      // 24: vcdeploy.v1.ReauthRequest
	(*ReauthResponse)(nil),     // 25: vcdeploy.v1.ReauthResponse
	(*StreamRepoRequest)(nil),  // 26: vcdeploy.v1.StreamRepoRequest
	(*RepoChunk)(nil),          // 27: vcdeploy.v1.RepoChunk
	nil,                        // 28: vcdeploy.v1.RegisterRequest.LabelsEntry
	nil,                        // 29: vcdeploy.v1.DeployCommand.EnvVarsEntry
	nil,                        // 30: vcdeploy.v1.HealthCheckCommand.HeadersEntry
}
var file_api_proto_agent_proto_depIdxs = []int32{
	28, // 0: vcdeploy.v1.RegisterRequest.labels:type_name -> vcdeploy.v1.RegisterRequest.LabelsEntry
	3,  // 1: vcdeploy.v1.RegisterRequest.capabilities:type_name -> vcdeploy.v1.AgentCapabilities
	6,  // 2: vcdeploy.v1.HeartbeatRequest.stats:type_name -> vcdeploy.v1.AgentStats
	20, // 3: vcdeploy.v1.HeartbeatRequest.active_deployments:type_name -> vcdeploy.v1.DeploymentStatus
	8,  // 4: vcdeploy.v1.HeartbeatResponse.update_available:type_name -> vcdeploy.v1.UpdateNotification
	20, // 5: vcdeploy.v1.AgentMessage.deployment_status:type_name -> vcdeploy.v1.DeploymentStatus
	21, // 6: vcdeploy.v1.AgentMessage.deployment_log:type_name -> vcdeploy.v1.DeploymentLog
	22, // 7: vcdeploy.v1.AgentMessage.command_result:type_name -> vcdeploy.v1.CommandResult
	23, // 8: vcdeploy.v1.AgentMessage.agent_ready:type_name -> vcdeploy.v1.AgentReady
	10, // 9: vcdeploy.v1.AgentMessage.update_result:type_name -> vcdeploy.v1.UpdateResult
	11, // 10: vcdeploy.v1.AgentMessage.health_check_result:type_name -> vcdeploy.v1.HealthCheckResult
	14, // 11: vcdeploy.v1.MasterMessage.deploy_command:type_name -> vcdeploy.v1.DeployCommand
	17, // 12: vcdeploy.v1.MasterMessage.rollback_command:type_name -> vcdeploy.v1.RollbackCommand
	18, // 13: vcdeploy.v1.MasterMessage.cancel_command:type_name -> vcdeploy.v1.CancelCommand
	19, // 14: vcdeploy.v1.MasterMessage.health_check_command:type_name -> vcdeploy.v1.HealthCheckCommand
	13, // 15: vcdeploy.v1.MasterMessage.update_command:type_name -> vcdeploy.v1.UpdateCommand
	15, // 16: vcdeploy.v1.DeployCommand.settings:type_name -> vcdeploy.v1.DeploymentSettings
	29, // 17: vcdeploy.v1.DeployCommand.env_vars:type_name -> vcdeploy.v1.DeployCommand.EnvVarsEntry
	16, // 18: vcdeploy.v1.DeployCommand.reload_services:type_name -> vcdeploy.v1.ServiceReload
	16, // 19: vcdeploy.v1.RollbackCommand.reload_services:type_name -> vcdeploy.v1.ServiceReload
	30, // 20: vcdeploy.v1.HealthCheckCommand.headers:type_name -> vcdeploy.v1.HealthCheckCommand.HeadersEntry
	0,  // 21: vcdeploy.v1.DeploymentStatus.state:type_name -> vcdeploy.v1.DeploymentState
	1,  // 22: vcdeploy.v1.DeploymentLog.level:type_name -> vcdeploy.v1.LogLevel
	2,  // 23: vcdeploy.v1.AgentService.Register:input_type -> vcdeploy.v1.RegisterRequest
	9,  // 24: vcdeploy.v1.AgentService.Connect:input_type -> vcdeploy.v1.AgentMessage
	5,  // 25: vcdeploy.v1.AgentService.Heartbeat:input_type -> vcdeploy.v1.HeartbeatRequest
	24, // 26: vcdeploy.v1.AgentService.Reauthenticate:input_type -> vcdeploy.v1.ReauthRequest
	26, // 27: vcdeploy.v1.AgentService.StreamRepoArchive:input_type -> vcdeploy.v1.StreamRepoRequest
	4,  // 28: vcdeploy.v1.AgentService.Register:output_type -> vcdeploy.v1.RegisterResponse
	12, // 29: vcdeploy.v1.AgentService.Connect:output_type -> vcdeploy.v1.MasterMessage
	7,  // 30: vcdeploy.v1.AgentService.Heartbeat:output_type -> vcdeploy.v1.HeartbeatResponse
	25, // 31: vcdeploy.v1.AgentService.Reauthenticate:output_type -> vcdeploy.v1.ReauthResponse
	27, // 32: vcdeploy.v1.AgentService.StreamRepoArchive:output_type -> vcdeploy.v1.RepoChunk
	28, // [28:33] is the sub-list for method output_type
	23, // [23:28] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_api_proto_agent_proto_init() }
func file_api_proto_agent_proto_init() {
	if File_api_proto_agent_proto != nil {
		return
	}
	file_api_proto_agent_proto_msgTypes[7].OneofWrappers = []any{
		(*AgentMessage_DeploymentStatus)(nil),
		(*AgentMessage_DeploymentLog)(nil),
		(*AgentMessage_CommandResult)(nil),
		(*AgentMessage_AgentReady)(nil),
		(*AgentMessage_UpdateResult)(nil),
		(*AgentMessage_HealthCheckResult)(nil),
	}
	file_api_proto_agent_proto_msgTypes[10].OneofWrappers = []any{
		(*MasterMessage_DeployCommand)(nil),
		(*MasterMessage_RollbackCommand)(nil),
		(*MasterMessage_CancelCommand)(nil),
		(*MasterMessage_HealthCheckCommand)(nil),
		(*MasterMessage_UpdateCommand)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agent_proto_rawDesc), len(file_api_proto_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_agent_proto_goTypes,
		DependencyIndexes: file_api_proto_agent_proto_depIdxs,
		EnumInfos:         file_api_proto_agent_proto_enumTypes,
		MessageInfos:      file_api_proto_agent_proto_msgTypes,
	}.Build()
	File_api_proto_agent_proto = out.File
	file_api_proto_agent_proto_goTypes = nil
	file_api_proto_agent_proto_depIdxs = nil
}
