package e2e
//go:build e2e

package e2e




























































































































































































}	})		}			t.Errorf("expected limit 10, got %d", result.Limit)		if result.Limit != 10 {		}			t.Fatalf("failed to decode response: %v", err)		if err != nil {		result, err := testutil.DecodePaginatedJSON(resp)		ctx.Assertions.StatusOK(resp)		defer resp.Body.Close()		}			t.Fatalf("request failed: %v", err)		if err != nil {		resp, err := ctx.Client.Get("/api/v1/audit?limit=10")	t.Run("audit with limit", func(t *testing.T) {	ctx.MustLogin(cfg.AdminUsername, cfg.AdminPassword)	cfg := testutil.GetConfig()	ctx := setupTest(t)func TestAuditPagination(t *testing.T) {// TestAuditPagination tests the audit endpoint pagination specifically.}	}		t.Errorf("totalCount changed between requests: %d vs %d", result1.TotalCount, result2.TotalCount)	if result1.TotalCount != result2.TotalCount {	// totalCount should be consistent	}		t.Fatalf("failed to decode second response: %v", err)	if err != nil {	result2, err := testutil.DecodePaginatedJSON(resp2)	defer resp2.Body.Close()	}		t.Fatalf("second request failed: %v", err)	if err != nil {	resp2, err := ctx.Client.Get("/api/v1/users?limit=1&offset=1")	// Get second page	}		t.Fatalf("failed to decode first response: %v", err)	if err != nil {	result1, err := testutil.DecodePaginatedJSON(resp1)	defer resp1.Body.Close()	}		t.Fatalf("first request failed: %v", err)	if err != nil {	resp1, err := ctx.Client.Get("/api/v1/users?limit=1&offset=0")	// Get first page	ctx.MustLogin(cfg.AdminUsername, cfg.AdminPassword)	cfg := testutil.GetConfig()	ctx := setupTest(t)func TestPaginationConsistency(t *testing.T) {// TestPaginationConsistency verifies totalCount stays consistent across paginated requests.}	}		})			})				}					t.Errorf("totalCount should be non-negative even with large offset, got %d", result.TotalCount)				if result.TotalCount < 0 {				// But totalCount should still reflect actual count				}					t.Errorf("expected 0 items with large offset, got %d", len(result.Items))				if len(result.Items) != 0 {				// With large offset, should have 0 items				}					t.Fatalf("failed to decode response: %v", err)				if err != nil {				result, err := testutil.DecodePaginatedJSON(resp)				ctx.Assertions.StatusOK(resp)				defer resp.Body.Close()				}					t.Fatalf("request failed: %v", err)				if err != nil {				resp, err := ctx.Client.Get(ep.endpoint + "?offset=999999")			t.Run("large offset returns empty items", func(t *testing.T) {			})				}					t.Errorf("expected offset 0, got %d", result.Offset)				if result.Offset != 0 {				}					t.Fatalf("failed to decode response: %v", err)				if err != nil {				result, err := testutil.DecodePaginatedJSON(resp)				ctx.Assertions.StatusOK(resp)				defer resp.Body.Close()				}					t.Fatalf("request failed: %v", err)				if err != nil {				resp, err := ctx.Client.Get(ep.endpoint + "?limit=5&offset=0")			t.Run("offset pagination", func(t *testing.T) {			})				}					t.Errorf("expected at most 5 items, got %d", len(result.Items))				if len(result.Items) > 5 {				// Items should not exceed limit				}					t.Errorf("expected limit 5, got %d", result.Limit)				if result.Limit != 5 {				}					t.Fatalf("failed to decode response: %v", err)				if err != nil {				result, err := testutil.DecodePaginatedJSON(resp)				ctx.Assertions.StatusOK(resp)				defer resp.Body.Close()				}					t.Fatalf("request failed: %v", err)				if err != nil {				resp, err := ctx.Client.Get(ep.endpoint + "?limit=5")			t.Run("custom limit", func(t *testing.T) {			})				}					t.Errorf("totalCount should be non-negative, got %d", result.TotalCount)				if result.TotalCount < 0 {				}					t.Errorf("offset should be non-negative, got %d", result.Offset)				if result.Offset < 0 {				}					t.Errorf("limit should be positive, got %d", result.Limit)				if result.Limit <= 0 {				// Verify pagination structure				}					t.Fatalf("failed to decode response: %v", err)				if err != nil {				result, err := testutil.DecodePaginatedJSON(resp)				ctx.Assertions.StatusOK(resp)				defer resp.Body.Close()				}					t.Fatalf("request failed: %v", err)				if err != nil {				resp, err := ctx.Client.Get(ep.endpoint)			t.Run("default pagination", func(t *testing.T) {		t.Run(ep.name, func(t *testing.T) {	for _, ep := range endpoints {	}		{"api-keys", "/api/v1/api-keys"},		{"secrets", "/api/v1/secrets"},		{"deployments", "/api/v1/deployments"},		{"agents", "/api/v1/agents"},		{"projects", "/api/v1/projects"},		{"users", "/api/v1/users"},	}{		endpoint string		name     string	endpoints := []struct {	// Test endpoints that return paginated responses	ctx.MustLogin(cfg.AdminUsername, cfg.AdminPassword)	// Login as admin	cfg := testutil.GetConfig()	ctx := setupTest(t)func TestPaginationEndpoints(t *testing.T) {// TestPaginationEndpoints tests pagination behavior across all paginated endpoints.)	"github.com/BlackOrder/vcdeploy/tests/testutil"	"testing"import (