#!/bin/sh
# OpenRC init script for VCDeploy Master

name="vcdeploy-master"
description="VCDeploy Master Server"
supervisor="supervise-daemon"

command="/usr/local/bin/vcdeploy"
command_args="master start"
command_user="vcdeploy:vcdeploy"
command_background="yes"

pidfile="/run/${name}.pid"
output_log="/var/log/vcdeploy/master.log"
error_log="/var/log/vcdeploy/master.error.log"

depend() {
    need net
    after firewall
}

start_pre() {
    checkpath --directory --owner vcdeploy:vcdeploy --mode 0755 /var/lib/vcdeploy
    checkpath --directory --owner vcdeploy:vcdeploy --mode 0755 /var/log/vcdeploy
    checkpath --directory --owner root:vcdeploy --mode 0750 /etc/vcdeploy
}
